language: node_js
node_js:
- node
deploy:
  provider: npm
  api_key:
    secure: NxsksJbEfJ58gosjKw2+N6HAER2zCa9QWxWKAh+X/DrbL683JJR5XBeVZIy1+SYL+22RWaZTnf0tp52VexddUGIqoJaGxoCVwP9G1H89iuK5d8UCHYCPi90OTqTpIDw7mdfUFPIgYC9NALz6CPMoecaxhNzv+bhrwyb9W2kwngXkrXeEmo6uhqlPE0ICZYpuhq+HjeebUp4Lu5MrOTIchobWTESblF5y5pkS53oDo/VDrrq/mryRXQeglKCT1uzXVlA/wEAzEZEpbbAODlGTAE0gh8NhzIhMoW1QxBDBTpUgea3hPefqc6D0L0ejt7/w28s4e9UYlF2Zt9FMxrlkVovF9JJunnGv4ZokV0zkCjiQCuLjo7rCp+nIvcczl01More5FsRBX632B+Lw4bh9mHqqNe5A4sqCPz9h5RZg1OmOjT9hH76IuPWfymZ3SUwH3ilwagI+o/0iklh7d1bkw4dVjGcjp4DDNsEobTQlYwX2S33PUwLABIjhDM0DWXvhEdJ8vMYvGXAkD7T5I4et/92OoIajIArgbQQYK/LoDW7NqQZyIUUGC2zTGF3fRM7wFi8LxrZG67nu3fOvtBApybRy2zdYL1/9QEJNYQRPvDlUhSmHrWcIMRWKGmbDlGklVP5E42/AGz4mY6zoq5mkeJ5HNazXCMoCO9jr+3iVGMU=
